abstract: Provides basic first-pass API testing for large class trees
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Test-ClassAPI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Inspector: 1.12
  Config::Tiny: 2.00
  File::Spec: 0.83
version: 1.03
